name: Auto commit

on:

  push:
    branches:
      - main
      
  schedule:
  - cron: "*/10 * * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "mike@mikeowino.com"
          git config --local user.name "MikeOwino"
          git add -A
          
          arr[0]="tf"
          arr[1]="tf"
          arr[2]="tf"
          arr[3]="tf"
          arr[4]="tf"
          arr[5]="tf"
          arr[6]="tf"
          arr[7]="tf"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
